# -*- coding: utf-8 -*-
"""Python 1 Hands on Condition Handling case.ipynb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OTbgIHtnkBTaPAtMzJCH-Dho_ZOle955

## **Python 1 | Hands on Condition Handling case**

**Assignment 1**

Write a program to change vocal word ("a,i,u,e,o") into "a" .Example:

Input:

lirik = "balonku ada lima"

Output:

"balanka ada lama"
"""

vocals = "a,i,u,e,o"
hasil = ""
text = input("masukkan text :")
for char in text :
  if char in vocals:
    hasil += 'a'
  else :
    hasil += char


print("hasil : " + hasil)

"""**Assignment 2**

Write a program to check student attendance. A student will not be allowed to sit an exam if his/her attendance is less than 75%. Example:

Input:

Class_held = 20

Student = [“Asnawi”, “Haaland”, “Hazard”, “Maudy Ayunan”,  “Marselino”, “Dembele”]

Class_attended = [18, 19, 10, 20, 17, 13]

Output:

Kehadiran asnawi lebih dari 75%, dapat mengikuti ujian cunin

Kehadiran hazard kurang dari 75%, tidak dapat mengikuti ujian cunin

Kehadiran dembele kurang dari 75%, tidak dapat mengikuti ujian cunin


"""

def check_attendance(class_held, students, class_attended):
    for i in range(len(students)):
        attendance_percentage = (class_attended[i] / class_held) * 100

        if attendance_percentage >= 75:
            print(f"Kehadiran {students[i]} lebih dari 75%, dapat mengikuti ujian cunin")
        else:
            print(f"Kehadiran {students[i]} kurang dari 75%, tidak dapat mengikuti ujian cunin")

# Example input
Class_held = int(input("Enter the number of students: "))
Num_students = int(input("Enter the name of student "))

Students = []
Class_attended = []

for i in range(Num_students):
    student_name = input(f"Name of student-{i + 1}: ")
    attendance = int(input(f"Enter the attendance for {student_name}: "))

    Students.append(student_name)
    Class_attended.append(attendance)

# Check attendance
check_attendance(Class_held, Students, Class_attended)